import * as langium from 'langium'
import * as LSP from 'langium/lsp'

import { TaoLangGeneratedModule, TaoLangGeneratedSharedModule } from '@tao-compiler/gen-tao-parser/module'

import { registerValidationChecks, TaoLangValidator } from '@tao-compiler/validation/tao-lang-validator.js'

/**
 * Declaration of custom services - add your own service classes here.
 */
export type TaoAddedServices = {
  validation: {
    TaoLangValidator: TaoLangValidator
  }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type TaoServices = LSP.LangiumServices & TaoAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const TaoModule: langium.Module<TaoServices, LSP.PartialLangiumServices & TaoAddedServices> = {
  validation: {
    TaoLangValidator: () => new TaoLangValidator(),
  },
}

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createTaoServices(context: LSP.DefaultSharedModuleContext): {
  shared: LSP.LangiumSharedServices
  Tao: LSP.LangiumServices
} {
  const shared = langium.inject(
    LSP.createDefaultSharedModule(context),
    TaoLangGeneratedSharedModule,
  )
  const Tao = langium.inject(
    LSP.createDefaultModule({ shared }),
    TaoLangGeneratedModule,
    TaoModule,
  )
  shared.ServiceRegistry.register(Tao)
  registerValidationChecks(Tao)
  if (!context.connection) {
    // We don't run inside a language server
    // Therefore, initialize the configuration provider instantly
    shared.workspace.ConfigurationProvider.initialized({})
  }
  return { shared, Tao }
}
